import { Component, OnInit, Input, Output, EventEmitter, ViewChild, ElementRef, Inject } from '@angular/core';
// import { Store } from '@ngrx/store';
// import { AppState } from 'src/app/app.reducer';
// import { TranslateService } from '@ngx-translate/core';
// import { ActivarLoadingAction, DesactivarLoadingAction } from 'src/app/shared/componentes/loading/store/loading.actions';
// import { MatDialog, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
// import { IUser } from 'src/app/core/auth/IUser';
// import * as pdfMake from "pdfmake/build/pdfmake";
// import * as pdfFonts from "pdfmake/build/vfs_fonts";
// import htmlToPdfmake from "html-to-pdfmake"
// import { bootstrapStyles } from '../styles';
// (pdfMake as any).vfs = pdfFonts.pdfMake.vfs;
import jspdf, { jsPDF } from 'jspdf'
import html2canvas from 'html2canvas'
import { ConversorPDFService } from './conversor-pdf.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  
  @ViewChild('pdfAlbaranEntregaJazztel') pdfAlbaranEntregaJazztel!: ElementRef;

  data: any;
  contador:number = 0;
  mostrarSeparador:boolean = false;
  constructor(
    private conversorPDF : ConversorPDFService
    // private store: Store<AppState>,
    // public translate: TranslateService,
    // public dialog: MatDialogRef<AlbaranEntregaJazztelComponent>,
    // @Inject(MAT_DIALOG_DATA) public albaran: any
  ) {
    this.data = [
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3003129,
      nserie: 861408068905085,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'XIAOMI REDMI NOTE 11S 5G 128GB NEGRO',
      cantidad: 1
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      },
      {nombreCliente: "BEATRIZ DIAZ TRUEBA",
      numeroPeticion: 51034038,
      nif: "50208432-F",
      bultos: 45,
      direccion: "(24H) MADRID SUC 4. CARABANCHEL BAJO CALLE GENERAL RICARDOS, 212 - CP:28025 MADRID",
      peso: 0.50,
      codigoPostal: 28025,
      poblacion: "MADRID",
      textoFechaEntrega: "F. Entrega:",
      fechaPrevistaEntrega: "02/03/2023",
      provincia: "MADRID",
      referencia: 3248634,
      nserie: 546756768645670,
      textoGarantia: 'Por favor conserve este documento, es imprescindible para ejercer la garantía. Recuerda que si tu pedido ha sufrido daños durante el transporte, dispones de 48h hábiles para solicitar su sustitución llamando al 1565, e indicando “equipo averiado en la entrega”.',
      descripcion: 'SAMSUNG GALAXY J7 128GB',
      cantidad: 4
      }
    ]
    // this.store.select('lang').subscribe(lang => {
    //   if (lang.lang) {
    //     this.translate.setDefaultLang(lang.lang);
    //     this.translate.use(lang.lang);
    //   }
    // });    

  }

  ngOnInit() {
    

    // this.store.dispatch(new DesactivarLoadingAction());
  }

  // convertirHTMLaPDF(anchoMarco:number, anchoContenido:number, nombrePDF:string, elemento:any) {
  //   const conversor = new jsPDF('p', 'px', 'a4');
    
  //   conversor.html(this.pdfAlbaranEntregaJazztel.nativeElement, {
  //     callback : function(doc){
  //     conversor.save(nombrePDF);},
  //   x:10,
  //   y:10,
  //   width:anchoContenido,
  //   windowWidth:anchoMarco
  // });}
  cositas(){
    // this.comprobarVisibilidadSeparador();
    this.conversorPDF.convertirHTMLaPDF(1100, 600, 'pdfConvertido',this.pdfAlbaranEntregaJazztel)
    var elemento = document.getElementById("separador");

// Obtiene el rectángulo del componente en relación con la ventana del navegador
    
    console.log(this.conversorPDF.contador)
  }
  incrementarContador(){
    this.conversorPDF.contador++;
    
  }
  // comprobarVisibilidadSeparador(){
  //   console.log("aaaaaaaaaa")
  //   var referencia = document.getElementById("referencia");
  //   var separadorAltura = document.getElementById("separadorAltura");
  //   if(referencia?.clientHeight > separadorAltura?.clientHeight){
  //     console.log("vvvvv")
  //     this.mostrarSeparador = true;
      
  //   }else{
  //     this.mostrarSeparador = false
  //   }
  // }

    // const divConvertible = this.elementoRef.nativeElement;
    // html2canvas(divConvertible).then(canvas => {
    //   const imgData = canvas.toDataURL('image/jpeg');
    //   conversor.addImage(imgData, 'JPEG', 10, 10,500,500, '', 'NONE', 0);
    //   conversor.save('archivo.pdf');
    // });
  
}
